#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1457383678                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Mądrość rodzi się w ciszy

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Praktyka
    description                           : Najlepiej kiedy możemy Medytacji poświęcić konkretny czas, przestrzeń i godzinę. Ale bardzo często medytujemy w drodze do pracy, pociąg, samolot, czekanie na przystanku. Praktyka to zegar medytacyjny oraz modlitwę na rozpoczęcie sesji. Możesz ustawić czas według własnych chęci i możliwości. Warte podkreślenia jest że po rozpoczęciu sesji możesz wygasić telefon i czekać w skupieniu na gong.
    fontawesome_icon_name                 : bell
    
  - title                                 : Czytania
    description                           : “Cisza” proponuje medytację w duchu lubińskim. Lubiń to klasztor benedyktynów gdzie pierwsze spotkania medytacyjne organizowali nieżyjący już o. Jan Bereza, po nim o. Maksymilian Nawara oraz Dariusz Hybel. Można też uznać za pierwszych mnichów Ojców Pustyni którzy jako pierwsi pozostawili świadectwo i piękną tradycję Modlitwy Serca. W Czytaniach użytkownik odnajdzie codzienny psalm oraz Ewangelię. Może z nich skorzystać przed sesją albo sięgać w dowolnym momencie.
    fontawesome_icon_name                 : bookmark

  - title                                 : Formacja
    description                           : Chcielibyśmy tą aplikacją nie tylko pomagać w codziennej medytacji ale też ją popularyzować. Postanowiliśmy więc wzbogacić jej zawartość o krótkie teksty jak w praktyce medytować, oraz jaka jest historia Modlitwy Serca. Dodaliśmy też listę polecanych książek oraz filmy z ośrodka lubińskiego.
    fontawesome_icon_name                 : user-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#3B3D40"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FD9600"
feature_icons_background_color            : "#3B3D40"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
